spring:
    datasource:
        platform: mysql
        url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/ivbase?useUnicode=yes&characterEncoding=UTF-8
        username: ${RDS_USERNAME:root}
        password: ${RDS_PASSWORD:1234}
        driverClassName: com.mysql.cj.jdbc.Driver
    thymeleaf:
        enabled: false 
    servlet:
        multipart:
            max-file-size: 500MB
            max-request-size: 500MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        require: true
logging:
    level: 
        ROOT: WARN
server:
    forward-headers-strategy: framework
    port: 5000
    tomcat:
        max-swallow-size: -1
