spring:
    security:
        oauth2:
            client:
                registration: 
                    facebook:
                        clientId: 591447728362435
                        clientSecret: a8fc749d01bb516304c33afbdf48551b   
                provider:
                    facebook:
                        authorization-uri: https://www.facebook.com/v6.0/dialog/oauth
                        token-uri: https://graph.facebook.com/v6.0/oauth/access_token

