spring:
    datasource:
        platform: mysql
        url: jdbc:mysql://db4free.net:3306/ivbase
        username: adminivb
        password: swp493_g4
        driverClassName: com.mysql.cj.jdbc.Driver
    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: 591447728362435
                        client-secret: a8fc749d01bb516304c33afbdf48551b
                        client-authentication-method: basic
                        access-token: 591447728362435|ljIUVkQfWKXxtkzrRUfTPCcxxOU
            resourceserver:
                indie:
                    introspection-uri: http://localhost:8080/introspect
                    introspection-client-id: client
                    introspection-client-secret: secret
    jpa:
        show-sql: true
server:
  forward-headers-strategy: framework
  port: 5000
