spring:
    datasource:
        platform: mysql
        url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/ivbase
        username: ${RDS_USERNAME:root}
        password: ${RDS_PASSWORD:1234}
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
    servlet:
        multipart:
            max-file-size: 500MB
            max-request-size: 500MB
server:
    forward-headers-strategy: framework
    port: 5000
    tomcat:
        max-swallow-size: -1
