spring:
    datasource:
        platform: mysql
        url: jdbc:mysql://db4free.net:3306/ivbase
        username: adminivb
        password: swp493_g4
        driverClassName: com.mysql.cj.jdbc.Driver
    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: 130595185046801
                        client-secret: add6a7389aa169d1bb87637d4ea9d378
                        client-authentication-method: basic
                        access-token: 130595185046801|kJZiStPIhpbIdnJLr2oAqfaghUE
            resourceserver:
                indie:
                    introspection-uri: http://localhost:8080/introspect
                    introspection-client-id: client
                    introspection-client-secret: secret
    jpa:
        show-sql: true
server:
  forward-headers-strategy: framework
  port: 5000
