spring:
    datasource:
        platform: mysql
        url: jdbc:mysql://localhost:3306/vibase
        username: root
        password: 1234
        driverClassName: com.mysql.cj.jdbc.Driver
    security:
        oauth2:
            client:
                registration: 
                    facebook:
                        clientId: 591447728362435
                        clientSecret: a8fc749d01bb516304c33afbdf48551b   
server:
  forward-headers-strategy: framework
